# Generated by Django 4.1.5 on 2023-01-25 15:46

from django.db import migrations, models
import uuid
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=web.models.get_csv_file_path)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Csv file',
                'verbose_name_plural': 'Csv files',
                'db_table': 'web_csv_files',
                'ordering': ('date_added',),
            },
        ),
    ]
